# Generated by Django 5.1.4 on 2025-02-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_user'),
        ('userApps', '0002_userinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='userApps.userinformation'),
        ),
    ]
